name: sparkles_empire
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  carousel_pro: ^1.0.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - images/bk.jpg
   - images/bk2.jpg
   - images/bk3.jpg
   - images/bk4.jpg
   - images/bk5.jpg
   - images/bk6.jpg
   - images/bk7.jpg
   - images/bk8.jpg
   - images/shirts/shirt1.jpg
   - images/shirts/shirt2.jpg
   - images/shirts/shirt3.jpg
   - images/shirts/shirt4.jpg
   - images/shirts/shirt5.jpg
   - images/shirts/shirt6.jpg
   - images/shirts/shirt7.jpg
   - images/shoes/shoe1.jpg
   - images/shoes/shoe2.jpg
   - images/shoes/shoe3.jpg
   - images/shoes/shoe4.jpg
   - images/shoes/shoe5.jpg
   - images/shoes/shoe6.jpg
   - images/shoes/shoe7.jpg
   - images/shoes/shoe8.jpg
   - images/shorts/short1.jpg
   - images/shorts/short2.jpg
   - images/shorts/short3.jpg
   - images/watches/watch1.jpg
   - images/watches/watch2.jpg
   - images/watches/watch3.jpg
   - images/watches/watch4.jpg
   - images/watches/watch5.jpg
   - images/watches/watch6.jpg
   - images/watches/watch7.jpg
   - images/tshirt.png
   - images/dress.png
   - images/formal.png
   - images/informal.png
   - images/jeans.png
   - images/shoe.png
   - images/watch.png

  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

    
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
